export const jobKeys = {
    jobTitle: "title",
    jobDescription: "description",
    skillsRequired: "skills",
    jobIsActive: "is_active",
    jobType: "typeof",
    jobTimePeriod: "time_period",
    generalTerms: "general_terms",
    technicalSpecifications: "Technical_Specifications",
    paymentTerms: "Payment_terms",
    workflowOfJob: "workflow",
    others: "others",
    paymentForJob: "paymentForJob",
    othersInternJobType: "othersInternJobType",
    othersResearchAssociateJobType: "othersResearchAssociateJobType",
    othersFreelancerJobType: "othersFreelancerJobType",
}